name: python_for_data_science
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - folium
  - geopandas
  - holoviews
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - networkx
  - nodejs
  - pandas
  - python=3.7
  - scipy
  - seaborn
  - shapely
  - sqlalchemy
  - xarray
  - xlrd
